name: Test Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t working-stats-dashboard .

      - name: Run container from image
        run: |
          docker run -d -p 5000:5000 --name test-app working-stats-dashboard
          sleep 5
          curl --fail http://localhost:5000 || (docker logs test-app && exit 1)

