name: Test Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t community-app .

      - name: Run container and test
        run: |
          docker run -d -p 5000:5000 --name test-app community-app
          sleep 5
          curl --fail http://localhost:5000 || (docker logs test-app && exit 1)

      - name: Cleanup
        run: docker rm -f test-app

